# Generated by Django 2.1.7 on 2019-03-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loaction',
            field=models.CharField(default='My loaction default', max_length=120),
        ),
    ]
