# Generated by Django 2.1.7 on 2019-03-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190310_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(default='My job default', max_length=120),
        ),
    ]
